version: '3'
services:
  mongo_db:
    # https://hub.docker.com/_/mongo/
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - ./db:/data/db
      - ./configdb:/data/configdb
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongo
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: admin
  mongo_express:
    # https://hub.docker.com/_/mongo-express
    image: mongo-express
    ports:
      - 8081:8081
    restart: always
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: mongo
      ME_CONFIG_MONGODB_ADMINPASSWORD: password
